exts: with exts; [
  akashagarwal.markdown-meaningful-wordcount
  arrterian.nix-env-selector
  asuka.insertnumbers
  brunnerh.insert-unicode
  dhall.dhall-lang
  dhall.vscode-dhall-lsp-server
  esbenp.prettier-vscode
  haskell.haskell
  haskell.language-haskell
  janw4ld.lambda-black
  jnoortheen.nix-ide
  jsynowiec.vscode-insertdatestring
  ms-vsliveshare.vsliveshare
  rioj7.select-by
  rust-lang.rust-analyzer
  tamasfe.even-better-toml
  well-typed.haskell-debugger-extension
]
