exts: with exts; [
  akashagarwal.markdown-meaningful-wordcount
  arrterian.nix-env-selector
  asuka.insertnumbers
  brunnerh.insert-unicode
  dhall.dhall-lang
  dhall.vscode-dhall-lsp-server
  gruntfuggly.todo-tree
  esbenp.prettier-vscode
  haskell.haskell
  janw4ld.lambda-black
  jnoortheen.nix-ide
  jsynowiec.vscode-insertdatestring
  justusadam.language-haskell
  ms-vsliveshare.vsliveshare
  nwolverson.ide-purescript
  nwolverson.language-purescript
  rioj7.select-by
  rust-lang.rust-analyzer
  tamasfe.even-better-toml
]
