[[protocols]]
name = 'LG-AKB74475403'
protocol = 'nec'
variant = 'nec'
[protocols.scancodes]
0x408 = 'KEY_POWER'
0x4f0 = 'KEY_TV'
0x439 = 'KEY_SUBTITLE'
0x491 = 'KEY_A'
0x479 = 'KEY_R'
0x40b = 'KEY_AUX'
0x411 = 'KEY_1'
0x412 = 'KEY_2'
0x413 = 'KEY_3'
0x414 = 'KEY_4'
0x415 = 'KEY_5'
0x416 = 'KEY_6'
0x417 = 'KEY_7'
0x418 = 'KEY_8'
0x419 = 'KEY_9'
0x410 = 'KEY_0'
0x453 = 'KEY_LIST'
0x41a = 'KEY_V'
0x41e = 'KEY_FAVORITES'
0x4ab = 'KEY_G'
0x409 = 'KEY_MUTE'
0x402 = 'KEY_VOLUMEUP'
0x403 = 'KEY_VOLUMEDOWN'
0x400 = 'KEY_CHANNELUP'
0x401 = 'KEY_CHANNELDOWN'
0x420 = 'KEY_TEXT'
0x4aa = 'KEY_INFO'
0x421 = 'KEY_OPTION'
0x443 = 'KEY_SETUP'
0x445 = 'KEY_MENU'
0x440 = 'KEY_UP'
0x407 = 'KEY_LEFT'
0x406 = 'KEY_RIGHT'
0x441 = 'KEY_DOWN'
0x444 = 'KEY_OK'
0x428 = 'KEY_BACK'
0x45b = 'KEY_EXIT'
0x430 = 'KEY_MODE'
0x4bd = 'KEY_RECORD'
0x4b1 = 'KEY_STOP'
0x48f = 'KEY_REWIND'
0x4b0 = 'KEY_PLAY'
0x4ba = 'KEY_PLAYPAUSE'
0x48e = 'KEY_FORWARD'
0x472 = 'KEY_RED'
0x471 = 'KEY_GREEN'
0x463 = 'KEY_YELLOW'
0x461 = 'KEY_BLUE'
